### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by tardyp** [scanoss/audit-workbench#357]
Hello,

When running the workbench inside a corporate network protected by an http proxy, the scanner fails to connect to api server

![image](https://user-images.githubusercontent.com/109859/157196067-7ee4419a-3f9d-4510-9cb1-6bbfa418cbc2.png)

Unlike python ecosystem, the electron ecosystem is usually not proxy friendly by default.

I can see some packages that support autodetecting proxy. I haven't tested it.
https://www.npmjs.com/package/electron-proxy-agent

**Comment by francostramana** [comment]
Thank you @tardyp for you report. We're taking care of that. We are doing some tests with our proxies and it works correctly for us.

Could you do a simple test for us in the same network using directly scanner-js cli package? https://www.npmjs.com/package/scanoss

**Comment by woznik** [comment]
Hello
I just did a test after configuring my corporate proxy and sadly there is still a time out reaching the external server:
![image](https://user-images.githubusercontent.com/17202024/191132569-df14437c-517e-438d-9b60-48aa518285fc.png)
the same from cmd:
![image](https://user-images.githubusercontent.com/17202024/191132653-2a13bcbc-25ff-4c15-a340-a7574e9f6f01.png)

**Comment by francostramana** [comment]
Proxy support added in version 1.5.0. Thank you very much for your contribution.
