### ISSUE TITLE
'Identify All As' fails on a folder with 'No components were detected'

### ISSUE THREAD

**Issue by ksummerlin** [scanoss/audit-workbench#413]
We have several components in node_modules that are not identified. The SCANOSS tool marks them as "No components were detected" even though there are components below and a license file is in the folder for the component.

I was able to manually add the component using the "Identify Component" dialog. But when I attempt to use Identify All As on the folder, and select the newly added component definition, nothing happens. The tool simply ignores my attempt to identify the component.

The screenshot below shows the component I added manually '@actin/dls'.
<img width="696" alt="Screen Shot 2022-05-02 at 11 31 07 AM" src="https://user-images.githubusercontent.com/104603/166263137-d85c385b-4d6b-454e-b642-055a5d28a1a8.png">

**Comment by Roy-Paz** [comment]
Hello Kelly, thank you for contacting us!

We have created a feature request to provide the action you have requested. I.e. “Identify all files as…” on folders without matches.
SCANOSS will shortly add support for package dependency scanning. This data will be extracted from package files (i.e. package.json) and presented in the Audit Workbench UI for confirmation.
If you need any further info, please contact us at support@scanoss.com

Thank you!
Best Regards, 
Roy Paz
scanoss.com

**Comment by francostramana** [comment]
Added in version 1.5.0. Thank you very much for your contribution.
