### ISSUE TITLE
usability: no UI to see unidentified components

### ISSUE THREAD

**Issue by lucasgonze** [scanoss/audit-workbench#438]
Right click a folder and select "Accept".

If there are files that weren't identified, the Accept All dialog will show this warning:
"23 component(s) will not be identified as they do not have a license declared with the component. Please, identify them manually."

<img width="576" alt="image" src="https://user-images.githubusercontent.com/111581/171914522-ded0a580-7a71-4acd-ba79-daddfbb76b75.png">

However, there is no affordance in this dialog to see which components were not identified and perform manual verification..

**Comment by francostramana** [comment]
I really like it you proposal. I created a ticket in our backlog to discuss with the team.

Anyway, we plan to improve this dialog. It is not the final version. Users will be able to quickly fill in missing licenses.
