### ISSUE TITLE
UI: unable to select and copy text

### ISSUE THREAD

**Issue by lucasgonze** [scanoss/audit-workbench#447]
In a number of places in the UI there is raw text that I need to copy and paste to work with. For example, in this snippet I wanted to copy the "ace-aws-..." string into a ticket for future work, since it is long and error-prone to type. However, text is not selectable or copyable.

<img width="472" alt="image" src="https://user-images.githubusercontent.com/111581/173697642-818fb28f-c28b-464a-a69f-ab77e712ff06.png">

**Comment by brunodeangelis** [comment]
This is very good to know. We'll work on considering those accessibility functionalities more.

Thank you @lucasgonze!

**Comment by francostramana** [comment]
Hey @lucasgonze thanks again for your feedback. We enabled text selection in the important sections of the application. See [https://github.com/scanoss/audit-workbench/commit/da99d494e11e3574ef763bf05493749229cc4efc](https://github.com/scanoss/audit-workbench/commit/da99d494e11e3574ef763bf05493749229cc4efc)

It will be available in the next release planned for the following week.
