### ISSUE TITLE
feature: mark and annotate a work item

### ISSUE THREAD

**Issue by lucasgonze** [scanoss/audit-workbench#473]
In using scanoss to triage clearance work, there is a need to flag and annotate clearance problems that need to be resolved.  This allows the clearance team to distinguish between newly identified tasks and ones that have already been started. 

In my workflows on a particular code base, I write an issue for each clearance task. Later on, when I am reviewing "pending" items, it is cumbersome to look up the status of every file with an alert on it. 

<img width="245" alt="image" src="https://user-images.githubusercontent.com/111581/178569056-aa66bab2-c361-44de-b8da-18a26c44b361.png">

Ways you might approach this feature in the UI:
1. A free text field
2. A field for the URL of an issue
3. A checkbox or dropdown list to make a note of the current status

**Comment by francostramana** [comment]
Hi @lucasgonze. Thank for your feedback. We already have in our backlog a feature to make annotations over files and folders. I think is aligned with your suggestion. We will notify you when we start to work over that.

**Comment by lucasgonze** [comment]
+1
