### ISSUE TITLE
'%' in scanned file name makes GUI crash

### ISSUE THREAD

**Issue by alpianon** [scanoss/audit-workbench#536]
I'm currently reviewing https://github.com/kraj/meta-clang with ScanOSS, to identify files copied from 3rd party repos.

There are many files with a '%' character in the name, like this one:
![immagine](https://user-images.githubusercontent.com/3025020/200565276-e9c00022-5c9e-42f4-8066-5f7f845cf7c0.png)

Every time that I click on one of them, the gui disappears and becomes all grey

![immagine](https://user-images.githubusercontent.com/3025020/200565453-960b7ca6-b69f-4cc3-92b5-344cfd34aee9.png)

I'm using Workbench 1.3.3

**Comment by francostramana** [comment]
Thanks @alpianon for submit this issue. We will work immediately on this.

**Comment by francostramana** [comment]
Solved in https://github.com/scanoss/audit-workbench/commit/fa61662583b616d78d94a54e597c3a32481e054b

We will close this issue once new version is released.

**Comment by francostramana** [comment]
Solved in version 1.5.0. Thank you very much for your contribution.
