### ISSUE TITLE
bug: inaccurate package version 

### ISSUE THREAD

**Issue by lucasgonze** [scanoss/audit-workbench#573]
1. Create an empty Node project
2. `npm add @types/tapable@1.0.0` and examine package.json to verify the version:

```
  "dependencies": {
    "@types/tapable": "^1.0.0"
  }
```

Or skip steps 1 and 2 and use the attached zip file: [repro.zip](https://github.com/scanoss/audit-workbench/files/10514219/repro.zip)

3. In SCANOSS Audit Workbench create a project and add the directory of your Node project.  Inspect the detected contents.

Expect: @types/tapable@1.0.0

Actual: @types/tapable version is 2.2.1

![Untitled 2](https://user-images.githubusercontent.com/111581/214973816-674948d9-bf4b-433f-9dae-5d779333c026.jpg)

**Comment by lucasgonze** [comment]
After upgrading my app from 1.3.5 to 1.5.0, the issue was fixed.

**Comment by isasmendiagus** [comment]
Hello @lucasgonze, thanks for your comments.
As you explained, version 1.5.0 solves that problem.
