### ISSUE TITLE
ERROR engine scan failed

### ISSUE THREAD

**Issue by fredvisser** [scanoss/audit-workbench#575]
I'm trying to run the latest (1.5.0) version of SCANOSS Audit Workbench on a MacBook Pro (Apple M2 Pro), and quickly getting an error: `ERROR engine scan failed` when scanning a simple NPM project. 

I've tried to run the x86 and M1/M2 versions of the app, as well as version 1.4.0, and received the same or similar errors.

Running the app via the console gives the following log:

```console
$ /Applications/SCANOSS\ Audit\ Workbench.app/Contents/MacOS/SCANOSS\ Audit\ Workbench 
[ CONFIGMODULE ]: Override config file found
11:28:39.867 › [ WORKSPACE ]: Reading projects....
…
11:28:43.310 › [ WORKSPACE ]: Closing all opened projects
11:28:43.311 › [ BaseScannerTask init scanner]
11:28:43.466 › [ SCANNER ]: WFP Calculator starting...
11:28:43.755 › [ SCANNER ]: New WFP content
(node:16186) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `SCANOSS Audit Workbench --trace-warnings ...` to show where the warning was created)
11:28:43.863 › [ SCANNER ]: New WFP content
…
11:28:44.697 › [ SCANNER ]: Error reason ERROR_SERVER_SIDE: ERROR engine scan failed

11:28:44.876 › [ PROJECT ]: Project nimble saved
11:28:44.877 › [ PROJECT ]: Closing project nimble
11:28:45.078 › [SCANNER PIPELINE ERROR] Stage: Scanning error: ERROR engine scan failed

ERROR_SERVER_SIDE: ERROR engine scan failed

    at ze.dispatch (/Applications/SCANOSS Audit Workbench.app/Contents/Resources/app.asar/dist/main/webpack:/scanoss-workbench/node_modules/scanoss/build/module/sdk/scanner/Dispatcher/Dispatcher.js:113:29)
    at process.resolve (node:internal/process/task_queues:96:5)
    at /Applications/SCANOSS Audit Workbench.app/Contents/Resources/app.asar/dist/main/webpack:/scanoss-workbench/node_modules/p-queue/dist/index.js:163:21 {
  code: 500
}
```

Is this just a server side issue?
Thanks!

**Comment by fredvisser** [comment]
Hi @isasmendiagus - for sure!

<img width="680" alt="Screenshot 2023-02-15 at 3 55 50 PM" src="https://user-images.githubusercontent.com/1458528/219178061-6b8b5cce-0ac0-408e-9391-9eb61db7f61b.png">

[bad_request-1676498143589-99dffdf0-a5b2-4aa0-9494-e29ee035e551.txt](https://github.com/scanoss/audit-workbench/files/10748195/bad_request-1676498143589-99dffdf0-a5b2-4aa0-9494-e29ee035e551.txt)

Given the first error complained about a missing package.json file, I copied the repo package.json file into place, and got a slightly different error:
<img width="647" alt="Screenshot 2023-02-15 at 3 58 22 PM" src="https://user-images.githubusercontent.com/1458528/219179928-da682b6d-d11d-4c12-ba51-d0584814efc4.png">



[bad_request-1676498291432-e2b44dc6-2e23-4b1f-ab87-6a14fb8a594c.txt](https://github.com/scanoss/audit-workbench/files/10748196/bad_request-1676498291432-e2b44dc6-2e23-4b1f-ab87-6a14fb8a594c.txt)
[project.log](https://github.com/scanoss/audit-workbench/files/10748197/project.log)

**Comment by mscasso-scanoss** [comment]
Dear @fredvisser , thank you very much for report this issue. We have identified a problem with our scanning engine. Our servers are already updated, and you should be able to scan properly now. Could you try to resume the scan and let us know how was it?
